mountall: Support LSB
Change-Id: I03db7d8cb3f039baac43a7693d4387684b1f3010
Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>

diff --git a/mount-helper b/mount-helper
--- a/mount-helper
+++ b/mount-helper
@@ -1,9 +1,20 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:       mountall
+# Default-Start:  S
+# Default-Stop:
+# Description:    Mount all internal partitions in /etc/fstab
+### END INIT INFO
+
+# Don't exit on error status
+set +e
 
 # Uncomment below to see more logs
 # set -x
 
 source $(dirname $0)/disk-helper
+
+LOGFILE=/tmp/mountall.log
 
 do_part()
 {
@@ -108,10 +119,18 @@ mountall()
 	done < /etc/fstab
 }
 
-# Mount basic file systems firstly
-mount -a -t "proc,devpts,tmpfs,sysfs,debugfs,pstore"
+case "$1" in
+	start|"")
+		# Mount basic file systems firstly
+		mount -a -t "proc,devpts,tmpfs,sysfs,debugfs,pstore"
 
-LOGFILE=/tmp/mountall.log
+		mountall 2>&1 | tee $LOGFILE
+		echo "Log saved to $LOGFILE"
+		;;
+	*)
+		echo "Usage: mount-helper start" >&2
+		exit 3
+		;;
+esac
 
-mountall 2>&1 | tee $LOGFILE
-echo "Log saved to $LOGFILE"
+:
diff --git a/resize-helper b/resize-helper
--- a/resize-helper
+++ b/resize-helper
@@ -1,9 +1,20 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:       resizeall
+# Default-Start:  S
+# Default-Stop:
+# Description:    Resize all internal mounted partitions
+### END INIT INFO
+
+# Don't exit on error status
+set +e
 
 # Uncomment below to see more logs
 # set -x
 
 source $(dirname $0)/disk-helper
+
+LOGFILE=/tmp/resizeall.log
 
 do_part()
 {
@@ -60,7 +71,15 @@ resizeall()
 	done < /proc/mounts
 }
 
-LOGFILE=/tmp/resizeall.log
+case "$1" in
+	start|"")
+		resizeall 2>&1 | tee $LOGFILE
+		echo "Log saved to $LOGFILE"
+		;;
+	*)
+		echo "Usage: resize-helper start" >&2
+		exit 3
+		;;
+esac
 
-resizeall 2>&1 | tee $LOGFILE
-echo "Log saved to $LOGFILE"
+:
